# Generated by Django 5.2.11 on 2026-02-25 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('jugadas_basico', models.IntegerField(default=0)),
                ('jugadas_medio', models.IntegerField(default=0)),
                ('jugadas_avanzado', models.IntegerField(default=0)),
                ('tiempo_promedio', models.FloatField(default=0.0)),
                ('total_partidas', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(max_length=20)),
                ('resultado', models.CharField(max_length=10)),
                ('tiempo_segundos', models.IntegerField()),
                ('intentos_realizados', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
